CREATE TABLE Users (
  UserId INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  UserName VARCHAR(20) NOT NULL,
  Email VARCHAR(30) NOT NULL,
  DateCreated DATE
);

CREATE TABLE Questions (
  QuestionId INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  UserId INT NOT NULL,
  Title VARCHAR(100) NOT NULL,
  Body TEXT NOT NULL,
  CreatedAt DATE
);

CREATE TABLE Answers(
  AnswerId INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  QuestionId INT NOT NULL,
  UserId INT NOT NULL,
  CreatedAt DATE
);
