CREATE TABLE Users (
  UserId SERIAL PRIMARY KEY,
  UserName VARCHAR(20),
  Email VARCHAR(30),
  DateCreated TIMESTAMP
);

CREATE TABLE Questions (
  QuestionId SERIAL PRIMARY KEY,
  UserId INT NOT NULL,
  Title VARCHAR(100) NOT NULL,
  Body TEXT NOT NULL,
  CreatedAt TIMESTAMP
);

CREATE TABLE Answers(
  AnswerId SERIAL PRIMARY KEY,
  QuestionId INT NOT NULL,
  UserId INT NOT NULL,
  CreatedAt TIMESTAMP
);
